# Generated by Django 3.1.1 on 2021-04-06 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.SmallIntegerField(choices=[(1, 'Corporate Headoffice'), (2, 'Operations Department'), (3, 'Work Station'), (4, 'Marketing Division')], default='1')),
                ('Date_and_Time_of_Incident', models.DateTimeField()),
                ('Incident_location', models.TextField()),
                ('Initial_Severity', models.SmallIntegerField(choices=[(1, 'Mild'), (2, 'Modarate'), (3, 'Severe'), (4, 'Fatal')], default='1')),
                ('immediate_Ation_Taken', models.TextField()),
                ('Reportes_By', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
