# Generated by Django 3.1.1 on 2021-04-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='Incident_Department',
            field=models.TextField(default='jffj'),
        ),
        migrations.AddField(
            model_name='incident',
            name='Sub_Incident_Type',
            field=models.SmallIntegerField(choices=[(1, 'Environmental_Incident'), (2, 'Injurry//Illness'), (3, 'Property_Damage'), (4, 'Vehicle')], default='1'),
            preserve_default=False,
        ),
    ]
