# Generated by Django 3.1.1 on 2021-04-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20210407_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='suspected_Cause',
            field=models.TextField(default='hggh'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='Incident_Department',
            field=models.TextField(),
        ),
    ]
