# Generated by Django 3.1.1 on 2021-04-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_incident_sub_incident_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='Sub_Incident_Type',
            field=models.TextField(),
        ),
    ]
