# Generated by Django 3.1.1 on 2021-04-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20210407_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='Date_and_Time_of_Incident',
        ),
        migrations.AddField(
            model_name='incident',
            name='Date',
            field=models.DateField(default='2020-2-3'),
        ),
        migrations.AddField(
            model_name='incident',
            name='Time',
            field=models.TimeField(default='10:30'),
        ),
    ]
